name: musa-550-fall-2020
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - numpy=1.19.1
  - nodejs=13.13.0
  - black=19.10b0
  - jupyterlab_code_formatter=1.3.6
  - pandas=1.1.2
  - matplotlib=3.3.0
  - notebook=6.1.4
  - ipython=7.17.0
  - jupyterlab=2.2.8
  - pip=20.2.2
  - altair=4.1.0
  - seaborn=0.10.1
  - vega_datasets=0.8.0
  - vega=3.4.0
  - geopandas=0.8.1
  - descartes=1.1.0
  - mapclassify=2.3.0
  - contextily=1.0.0
  - bokeh=2.1.1
  - hvplot=0.6.0
  - holoviews=1.13.3
  - geoviews=1.8.1
  - xarray=0.16.0
  - datashader=0.11.1
  - param=1.9.3
  - panel=0.9.7
  - rasterio=1.1.5
  - rasterstats=0.14.0
  - earthpy=0.9.2
  - requests=2.24.0
  - cenpy=1.0.0.post4
  - selenium=3.141.0
  - beautifulsoup4=4.9.1
  - geckodriver=0.27.0
  - imageio=2.9.0
  - intake=0.6.0
  - intake-parquet=0.2.3
  - intake-xarray=0.3.1
  - dask=2.23.0
  - fastparquet=0.4.1
  - python-snappy=0.5.4
  - pyarrow=1.0.0
  - s3fs=0.5.0
  - tqdm=4.48.2
  - pandana=0.5.1
  - osmnx=0.15.1
  - networkx=2.4
  - scikit-learn=0.23.2
  - flask=1.1.2
  - dash=1.14.0
  - tweepy=3.9.0
  - textblob=0.15.3
  - nltk=3.4.4
  - rio-toa=0.3.0
  - rioxarray=0.0.31
  - missingno=0.4.2
  - jupyter-panel-proxy=0.1.0
  - pip:
      - us==2.0.2
      - carto2gpd==1.0.7
      - esri2gpd==1.0.7
      - osm2gpd==1.0.1
      - webdriver_manager==3.2.2
      - cartopy==0.18.0
