name: musa-550-fall-2020
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - numpy=1.19.*
  - nodejs
  - black=19.10b0
  - jupyterlab_code_formatter
  - pandas=1.1.*
  - matplotlib=3.3.0
  - notebook=6.1.*
  - ipython=7.17.*
  - jupyterlab=2.2.*
  - pip=20.2.2
  - altair=4.1.*
  - seaborn=0.10.*
  - vega_datasets=0.8.0
  - vega=3.4.0
  - geopandas=0.8.*
  - descartes=1.1.0
  - cartopy=0.18.0
  - mapclassify=2.3.*
  - contextily=1.0.*
  - bokeh=2.1.*
  - hvplot=0.6.*
  - holoviews=1.13.3
  - geoviews=1.8.1
  - xarray=0.16.0
  - datashader=0.11.1
  - pydeck=0.4.*
  - param=1.9.3
  - panel=0.9.7
  - rasterio=1.1.5
  - rasterstats=0.14.0
  - earthpy=0.9.2
  - requests=2.24.0
  - cenpy=1.0.*
  - selenium=3.141.0
  - beautifulsoup4=4.9.*
  - geckodriver=0.27.*
  - python-chromedriver-binary=84.*
  - imageio=2.9.0
  - intake=0.6.*
  - intake-parquet=0.2.3
  - intake-xarray=0.3.1
  - dask=2.23.*
  - fastparquet=0.4.1
  - python-snappy=0.5.4
  - pyarrow=1.0.0
  - s3fs=0.5.0
  - tqdm=4.48.*
  - pandana=0.5.1
  - osmnx=0.15.*
  - networkx=2.4
  - scikit-learn=0.23.*
  - flask=1.1.*
  - dash=1.14.*
  - tweepy=3.9.*
  - textblob=0.15.*
  - nltk=3.4.*
  - rio-toa=0.3.0
  - rioxarray=0.0.31
  - missingno=0.4.2
  - jupyter-panel-proxy=0.1.0
  - pip:
      - us==2.0.*
      - carto2gpd==1.0.*
      - esri2gpd==1.0.*
      - osm2gpd==1.0.*
